### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by liusida** [Pold87/academic-keyword-occurrence#15]
I cloned the repo and run the command, it says,

```
academic-keyword-occurrence$ python extract_occurrences.py 'bitcoin' 2000 2020
year,results
Traceback (most recent call last):
  File "extract_occurrences.py", line 75, in <module>
    html = get_range(search_term, start_date, end_date)
  File "extract_occurrences.py", line 51, in get_range
    num_results, success = get_num_results(search_term, date, date)
  File "extract_occurrences.py", line 19, in get_num_results
    handler = opener.open(request)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/liusida/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

```

**Comment by Pold87** [comment]
The script sends several requests to Google in a rather short time and Google restricts the number of requests, You can try and set `time.sleep(0.8)` to a higher value, for example, `time.sleep(3.0)` or reduce the size of your date range, that is, instead of `python extract_occurrences.py 'bitcoin' 2000 2020`, maybe try `python extract_occurrences.py 'bitcoin' 2010 2020`. If you continue to get the error, you may have to wait for some hours before you try again.

**Comment by liusida** [comment]
I figured out a way to work around this problem.
I copied the Headers from a browser which is viewing Google Scholar, and send requests to Google with those headers.

And yes, I changed the sleep time to be 2 seconds, just in case.

here is what I did:
https://github.com/liusida/Google-Scholar-Trends/blob/master/Google-Scholar-Trends.ipynb
